catalog:
  "@antfu/eslint-config": ^4.14.1
  "@changesets/cli": ^2.29.4
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@eslint/compat": ^1.3.0
  "@total-typescript/ts-reset": ^0.6.1
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^13.3.0
  "@vp-tw/eslint-config": ^0.1.5
  "@vp-tw/tsconfig": ^3.1.2
  commitizen: ^4.3.1
  cspell: ^9.1.1
  es-toolkit: ^1.38.0
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-package-json: ^0.40.0
  eslint-plugin-storybook: ^9.0.11
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^16.1.2
  pathe: ^2.0.3
  postcss-styled-syntax: ^0.7.1
  prettier: ^3.5.3
  read-pkg: ^9.0.1
  stylelint: ^16.20.0
  stylelint-config-idiomatic-order: ^10.0.0
  stylelint-config-standard: ^38.0.0
  stylelint-prettier: ^5.0.3
  tsdown: ^0.12.5
  tsx: ^4.20.3
  typescript: ^5.8.3
  url-join: ^5.0.0
  vite: npm:rolldown-vite@^6.3.21
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4

catalogMode: strict

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

packages:
  - packages/*

publicHoistPattern:
  - "@tsconfig/*"
